name: Deploy Cookie Bot Live

on:
  push:
    branches:
      - main # Triggers the deploy every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /app/Cookie-bot
            git pull origin main
            npm install --production
            pm2 restart index.js --name "Cookie-bot" || pm2 start index.js --name "Cookie-bot"
